### ISSUE TITLE
Return the highest mark of student

### ISSUE THREAD

**Issue by Deepakmukka1** [Deepakmukka1/microservices-js#2]
Create a route that give the highest mark of student

**Comment by falguni-k** [comment]
Hi, I would like to work on this issue. Please assign it to me.
Thanks!

**Comment by Deepakmukka1** [comment]
@falguni-k sure

**Comment by Deepakmukka1** [comment]
Please follow this https://opensource.com/article/19/7/create-pull-request-github to make a PR

**Comment by Deepakmukka1** [comment]
https://github.com/Deepakmukka1/microservices-js/pull/4
